[METHOD]
window = 5.0

[SPECTRONAUT]
precursor_mass = "FG.Mass"
precursor_mz = "FG.PrecMz"
precursor_charge = "FG.Charge"
retention_time = "EG.ApexRT"
retention_time_in_sec = false

[MATCHING]
mz_tolerance = 0.02
rt_tolerance = 0.01

[FILTERING]
total_intensity_threshold = 0.7
